spring.application.name=simple-api-and-wallet
server.port=8080

# MYSQL CONFIGURATION
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.url=jdbc:mysql://localhost:3306/fintech-db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#LIQUIBASE CONFIGURATION
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# JWT Configuration
jwt.secret=S3B2YzlkM2U3YTFkZjM0YmVkN2VjNjBmNWE5Yzg2MTIyZDNlNTQ5NGExY2Y5Y2JjY2Y5ODViMmQ5MTA1Mjg5
jwt.expiration=86400000


# EMAIL
spring.mail.host: smtp.gmail.com
spring.mail.port: 587
spring.mail.username: optic11051997@gmail.com
spring.mail.password: rpye xart ggqg gaax 
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true

email.from=optic11051997@gmail.com




