# Define all Docker services - PLATAFORMA LEGAL
services:

  # MySQL Service Configuration - Plataforma Legal
  mysql:
    image: mysql:8.0
    container_name: mysql-db-wallet
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fintech-db      
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Adminer Service Configuration - Plataforma Legal
  # LOGIN NO WEBSERVICE ADMINER LOCAL
  # System: MySQL/MariaDB
  # Server: mysql
  # username: root
  # password: root
  # database: ecommerce
  adminer:
    image: adminer:5.2.1
    container_name: adminer-walltet
    restart: always
    ports:
      - "8085:8080"
    depends_on:
      - mysql

  # REDIS SERVICE CONFIGURATION
  #redis:
   #image: redis:7.0
   #container_name: service_redis
   #restart: always
   #ports:
     #- "6379:6379"
   #command: ["redis-server", "--appendonly", "yes"]
   #volumes:
     #- redis_data:/data    

# KAFKA SERVICE CONFIGURATION
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.1
    container_name: zookeeper-walltet
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.7.1
    container_name: kafka-walltet
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      #Kafka listens on both ports
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_DOCKER://0.0.0.0:9093

      # Kafka tells host clients to use localhost:9092, docker clients to use kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_DOCKER://kafka:9093

      # Mapping the protocols
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

## KAFKA UI SERVICE CONFIGURATION
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui-walltet
    ports:
      - "8083:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
    depends_on:
      - kafka


volumes:
  mysql_data:
