version: "3.8"

services:

  # BACKEND SERVICE CONFIGURATION 
  backend:
    build:
      context: ../Simple-API-and-Wallet
      dockerfile: Dockerfile.yaml
    container_name: backend-wallet-service-prod
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
      kafka:
        condition: service_started

  # FRONTEND SERVICE CONFIGURATION
  frontend:
    build:
      context: ../Simple-API-Wallet_Frontend
      dockerfile: Dockerfile.yaml
    container_name: frontend-wallet-service-prod
    expose:
    - "4000"
    depends_on:
      - backend

  # MYSQL SERVICE CONFIGURATION
  mysql:
    image: mysql:8.0
    container_name: mysql-wallet-prod
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fintech-db
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ADMINER SERVICE CONFIGURATION
  adminer:
    image: adminer:5.2.1
    container_name: adminer-wallet-prod
    restart: always
    ports:
      - "8085:8080"
    depends_on:
      - mysql

  # REDIS SERVICE CONFIGURATION
  redis:
    image: redis:7.0
    container_name: redis-wallet-prod
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  # ZOOKEEPER SERVICE CONFIGURATION
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.1
    container_name: zookeeper-wallet-prod
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  # KAFKA SERVICE CONFIGURATION
  kafka:
    image: confluentinc/cp-kafka:7.7.1
    container_name: kafka-wallet-prod
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"   # optional (for debugging from host)
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  # KAFKA-UI SERVICE CONFIGURATION
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui-wallet-prod
    ports:
      - "8083:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: docker
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka

  # NGINX SERVICE CONFIGURATION
  nginx:
    image: nginx:alpine
    container_name: nginx-wallet
    ports:
      - "8088:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  mysql_data:
  redis_data: