### ANGULAR DOCKERFILE IMAGE

# Build Angular
FROM node:20 AS build

WORKDIR /app
COPY . .
RUN npm install
RUN npm run build --configuration production

# Serve with nginx
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80